// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: quoteMessages.proto

package stockwatch.messages;

public final class QuoteMessages {
  private QuoteMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface QuoteOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // required string id = 2;
    boolean hasId();
    String getId();
    
    // optional double lastPrice = 3;
    boolean hasLastPrice();
    double getLastPrice();
    
    // optional double percentageChange = 4;
    boolean hasPercentageChange();
    double getPercentageChange();
    
    // optional double open = 5;
    boolean hasOpen();
    double getOpen();
    
    // optional double low = 6;
    boolean hasLow();
    double getLow();
    
    // optional double high = 7;
    boolean hasHigh();
    double getHigh();
    
    // optional int32 volume = 8;
    boolean hasVolume();
    int getVolume();
    
    // optional string lastChangeTime = 9;
    boolean hasLastChangeTime();
    String getLastChangeTime();
    
    // optional int32 lop = 10;
    boolean hasLop();
    int getLop();
    
    // optional int32 lopChane = 11;
    boolean hasLopChane();
    int getLopChane();
    
    // optional string expirationDate = 12;
    boolean hasExpirationDate();
    String getExpirationDate();
  }
  public static final class Quote extends
      com.google.protobuf.GeneratedMessage
      implements QuoteOrBuilder {
    // Use Quote.newBuilder() to construct.
    private Quote(Builder builder) {
      super(builder);
    }
    private Quote(boolean noInit) {}
    
    private static final Quote defaultInstance;
    public static Quote getDefaultInstance() {
      return defaultInstance;
    }
    
    public Quote getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stockwatch.messages.QuoteMessages.internal_static_serialized_Quote_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stockwatch.messages.QuoteMessages.internal_static_serialized_Quote_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional double lastPrice = 3;
    public static final int LASTPRICE_FIELD_NUMBER = 3;
    private double lastPrice_;
    public boolean hasLastPrice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getLastPrice() {
      return lastPrice_;
    }
    
    // optional double percentageChange = 4;
    public static final int PERCENTAGECHANGE_FIELD_NUMBER = 4;
    private double percentageChange_;
    public boolean hasPercentageChange() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getPercentageChange() {
      return percentageChange_;
    }
    
    // optional double open = 5;
    public static final int OPEN_FIELD_NUMBER = 5;
    private double open_;
    public boolean hasOpen() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getOpen() {
      return open_;
    }
    
    // optional double low = 6;
    public static final int LOW_FIELD_NUMBER = 6;
    private double low_;
    public boolean hasLow() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public double getLow() {
      return low_;
    }
    
    // optional double high = 7;
    public static final int HIGH_FIELD_NUMBER = 7;
    private double high_;
    public boolean hasHigh() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getHigh() {
      return high_;
    }
    
    // optional int32 volume = 8;
    public static final int VOLUME_FIELD_NUMBER = 8;
    private int volume_;
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public int getVolume() {
      return volume_;
    }
    
    // optional string lastChangeTime = 9;
    public static final int LASTCHANGETIME_FIELD_NUMBER = 9;
    private java.lang.Object lastChangeTime_;
    public boolean hasLastChangeTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getLastChangeTime() {
      java.lang.Object ref = lastChangeTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          lastChangeTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getLastChangeTimeBytes() {
      java.lang.Object ref = lastChangeTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        lastChangeTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 lop = 10;
    public static final int LOP_FIELD_NUMBER = 10;
    private int lop_;
    public boolean hasLop() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public int getLop() {
      return lop_;
    }
    
    // optional int32 lopChane = 11;
    public static final int LOPCHANE_FIELD_NUMBER = 11;
    private int lopChane_;
    public boolean hasLopChane() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public int getLopChane() {
      return lopChane_;
    }
    
    // optional string expirationDate = 12;
    public static final int EXPIRATIONDATE_FIELD_NUMBER = 12;
    private java.lang.Object expirationDate_;
    public boolean hasExpirationDate() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getExpirationDate() {
      java.lang.Object ref = expirationDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          expirationDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getExpirationDateBytes() {
      java.lang.Object ref = expirationDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        expirationDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      id_ = "";
      lastPrice_ = 0D;
      percentageChange_ = 0D;
      open_ = 0D;
      low_ = 0D;
      high_ = 0D;
      volume_ = 0;
      lastChangeTime_ = "";
      lop_ = 0;
      lopChane_ = 0;
      expirationDate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lastPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, percentageChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, open_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeDouble(6, low_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, high_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, volume_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getLastChangeTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, lop_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, lopChane_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getExpirationDateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lastPrice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, percentageChange_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, open_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, low_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, high_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, volume_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getLastChangeTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, lop_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, lopChane_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getExpirationDateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stockwatch.messages.QuoteMessages.Quote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.Quote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stockwatch.messages.QuoteMessages.Quote prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stockwatch.messages.QuoteMessages.QuoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stockwatch.messages.QuoteMessages.internal_static_serialized_Quote_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stockwatch.messages.QuoteMessages.internal_static_serialized_Quote_fieldAccessorTable;
      }
      
      // Construct using stockwatch.messages.QuoteMessages.Quote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastPrice_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        percentageChange_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        open_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        low_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000020);
        high_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        volume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        lastChangeTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        lop_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        lopChane_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        expirationDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stockwatch.messages.QuoteMessages.Quote.getDescriptor();
      }
      
      public stockwatch.messages.QuoteMessages.Quote getDefaultInstanceForType() {
        return stockwatch.messages.QuoteMessages.Quote.getDefaultInstance();
      }
      
      public stockwatch.messages.QuoteMessages.Quote build() {
        stockwatch.messages.QuoteMessages.Quote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stockwatch.messages.QuoteMessages.Quote buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stockwatch.messages.QuoteMessages.Quote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stockwatch.messages.QuoteMessages.Quote buildPartial() {
        stockwatch.messages.QuoteMessages.Quote result = new stockwatch.messages.QuoteMessages.Quote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastPrice_ = lastPrice_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.percentageChange_ = percentageChange_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.open_ = open_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.low_ = low_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.high_ = high_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.lastChangeTime_ = lastChangeTime_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.lop_ = lop_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.lopChane_ = lopChane_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.expirationDate_ = expirationDate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stockwatch.messages.QuoteMessages.Quote) {
          return mergeFrom((stockwatch.messages.QuoteMessages.Quote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stockwatch.messages.QuoteMessages.Quote other) {
        if (other == stockwatch.messages.QuoteMessages.Quote.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasLastPrice()) {
          setLastPrice(other.getLastPrice());
        }
        if (other.hasPercentageChange()) {
          setPercentageChange(other.getPercentageChange());
        }
        if (other.hasOpen()) {
          setOpen(other.getOpen());
        }
        if (other.hasLow()) {
          setLow(other.getLow());
        }
        if (other.hasHigh()) {
          setHigh(other.getHigh());
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasLastChangeTime()) {
          setLastChangeTime(other.getLastChangeTime());
        }
        if (other.hasLop()) {
          setLop(other.getLop());
        }
        if (other.hasLopChane()) {
          setLopChane(other.getLopChane());
        }
        if (other.hasExpirationDate()) {
          setExpirationDate(other.getExpirationDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              id_ = input.readBytes();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lastPrice_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              percentageChange_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              open_ = input.readDouble();
              break;
            }
            case 49: {
              bitField0_ |= 0x00000020;
              low_ = input.readDouble();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              high_ = input.readDouble();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              volume_ = input.readInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              lastChangeTime_ = input.readBytes();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              lop_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              lopChane_ = input.readInt32();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              expirationDate_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // required string id = 2;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
      }
      
      // optional double lastPrice = 3;
      private double lastPrice_ ;
      public boolean hasLastPrice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getLastPrice() {
        return lastPrice_;
      }
      public Builder setLastPrice(double value) {
        bitField0_ |= 0x00000004;
        lastPrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastPrice() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastPrice_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double percentageChange = 4;
      private double percentageChange_ ;
      public boolean hasPercentageChange() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getPercentageChange() {
        return percentageChange_;
      }
      public Builder setPercentageChange(double value) {
        bitField0_ |= 0x00000008;
        percentageChange_ = value;
        onChanged();
        return this;
      }
      public Builder clearPercentageChange() {
        bitField0_ = (bitField0_ & ~0x00000008);
        percentageChange_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double open = 5;
      private double open_ ;
      public boolean hasOpen() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getOpen() {
        return open_;
      }
      public Builder setOpen(double value) {
        bitField0_ |= 0x00000010;
        open_ = value;
        onChanged();
        return this;
      }
      public Builder clearOpen() {
        bitField0_ = (bitField0_ & ~0x00000010);
        open_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double low = 6;
      private double low_ ;
      public boolean hasLow() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public double getLow() {
        return low_;
      }
      public Builder setLow(double value) {
        bitField0_ |= 0x00000020;
        low_ = value;
        onChanged();
        return this;
      }
      public Builder clearLow() {
        bitField0_ = (bitField0_ & ~0x00000020);
        low_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double high = 7;
      private double high_ ;
      public boolean hasHigh() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getHigh() {
        return high_;
      }
      public Builder setHigh(double value) {
        bitField0_ |= 0x00000040;
        high_ = value;
        onChanged();
        return this;
      }
      public Builder clearHigh() {
        bitField0_ = (bitField0_ & ~0x00000040);
        high_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int32 volume = 8;
      private int volume_ ;
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public int getVolume() {
        return volume_;
      }
      public Builder setVolume(int value) {
        bitField0_ |= 0x00000080;
        volume_ = value;
        onChanged();
        return this;
      }
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000080);
        volume_ = 0;
        onChanged();
        return this;
      }
      
      // optional string lastChangeTime = 9;
      private java.lang.Object lastChangeTime_ = "";
      public boolean hasLastChangeTime() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getLastChangeTime() {
        java.lang.Object ref = lastChangeTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          lastChangeTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setLastChangeTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        lastChangeTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearLastChangeTime() {
        bitField0_ = (bitField0_ & ~0x00000100);
        lastChangeTime_ = getDefaultInstance().getLastChangeTime();
        onChanged();
        return this;
      }
      void setLastChangeTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        lastChangeTime_ = value;
        onChanged();
      }
      
      // optional int32 lop = 10;
      private int lop_ ;
      public boolean hasLop() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public int getLop() {
        return lop_;
      }
      public Builder setLop(int value) {
        bitField0_ |= 0x00000200;
        lop_ = value;
        onChanged();
        return this;
      }
      public Builder clearLop() {
        bitField0_ = (bitField0_ & ~0x00000200);
        lop_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 lopChane = 11;
      private int lopChane_ ;
      public boolean hasLopChane() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public int getLopChane() {
        return lopChane_;
      }
      public Builder setLopChane(int value) {
        bitField0_ |= 0x00000400;
        lopChane_ = value;
        onChanged();
        return this;
      }
      public Builder clearLopChane() {
        bitField0_ = (bitField0_ & ~0x00000400);
        lopChane_ = 0;
        onChanged();
        return this;
      }
      
      // optional string expirationDate = 12;
      private java.lang.Object expirationDate_ = "";
      public boolean hasExpirationDate() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getExpirationDate() {
        java.lang.Object ref = expirationDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          expirationDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setExpirationDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        expirationDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearExpirationDate() {
        bitField0_ = (bitField0_ & ~0x00000800);
        expirationDate_ = getDefaultInstance().getExpirationDate();
        onChanged();
        return this;
      }
      void setExpirationDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        expirationDate_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:serialized.Quote)
    }
    
    static {
      defaultInstance = new Quote(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serialized.Quote)
  }
  
  public interface QuoteListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .serialized.Quote quote = 1;
    java.util.List<stockwatch.messages.QuoteMessages.Quote> 
        getQuoteList();
    stockwatch.messages.QuoteMessages.Quote getQuote(int index);
    int getQuoteCount();
    java.util.List<? extends stockwatch.messages.QuoteMessages.QuoteOrBuilder> 
        getQuoteOrBuilderList();
    stockwatch.messages.QuoteMessages.QuoteOrBuilder getQuoteOrBuilder(
        int index);
  }
  public static final class QuoteList extends
      com.google.protobuf.GeneratedMessage
      implements QuoteListOrBuilder {
    // Use QuoteList.newBuilder() to construct.
    private QuoteList(Builder builder) {
      super(builder);
    }
    private QuoteList(boolean noInit) {}
    
    private static final QuoteList defaultInstance;
    public static QuoteList getDefaultInstance() {
      return defaultInstance;
    }
    
    public QuoteList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stockwatch.messages.QuoteMessages.internal_static_serialized_QuoteList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stockwatch.messages.QuoteMessages.internal_static_serialized_QuoteList_fieldAccessorTable;
    }
    
    // repeated .serialized.Quote quote = 1;
    public static final int QUOTE_FIELD_NUMBER = 1;
    private java.util.List<stockwatch.messages.QuoteMessages.Quote> quote_;
    public java.util.List<stockwatch.messages.QuoteMessages.Quote> getQuoteList() {
      return quote_;
    }
    public java.util.List<? extends stockwatch.messages.QuoteMessages.QuoteOrBuilder> 
        getQuoteOrBuilderList() {
      return quote_;
    }
    public int getQuoteCount() {
      return quote_.size();
    }
    public stockwatch.messages.QuoteMessages.Quote getQuote(int index) {
      return quote_.get(index);
    }
    public stockwatch.messages.QuoteMessages.QuoteOrBuilder getQuoteOrBuilder(
        int index) {
      return quote_.get(index);
    }
    
    private void initFields() {
      quote_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getQuoteCount(); i++) {
        if (!getQuote(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < quote_.size(); i++) {
        output.writeMessage(1, quote_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < quote_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, quote_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stockwatch.messages.QuoteMessages.QuoteList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stockwatch.messages.QuoteMessages.QuoteList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stockwatch.messages.QuoteMessages.QuoteListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stockwatch.messages.QuoteMessages.internal_static_serialized_QuoteList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stockwatch.messages.QuoteMessages.internal_static_serialized_QuoteList_fieldAccessorTable;
      }
      
      // Construct using stockwatch.messages.QuoteMessages.QuoteList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getQuoteFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (quoteBuilder_ == null) {
          quote_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          quoteBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stockwatch.messages.QuoteMessages.QuoteList.getDescriptor();
      }
      
      public stockwatch.messages.QuoteMessages.QuoteList getDefaultInstanceForType() {
        return stockwatch.messages.QuoteMessages.QuoteList.getDefaultInstance();
      }
      
      public stockwatch.messages.QuoteMessages.QuoteList build() {
        stockwatch.messages.QuoteMessages.QuoteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stockwatch.messages.QuoteMessages.QuoteList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stockwatch.messages.QuoteMessages.QuoteList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stockwatch.messages.QuoteMessages.QuoteList buildPartial() {
        stockwatch.messages.QuoteMessages.QuoteList result = new stockwatch.messages.QuoteMessages.QuoteList(this);
        int from_bitField0_ = bitField0_;
        if (quoteBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            quote_ = java.util.Collections.unmodifiableList(quote_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.quote_ = quote_;
        } else {
          result.quote_ = quoteBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stockwatch.messages.QuoteMessages.QuoteList) {
          return mergeFrom((stockwatch.messages.QuoteMessages.QuoteList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stockwatch.messages.QuoteMessages.QuoteList other) {
        if (other == stockwatch.messages.QuoteMessages.QuoteList.getDefaultInstance()) return this;
        if (quoteBuilder_ == null) {
          if (!other.quote_.isEmpty()) {
            if (quote_.isEmpty()) {
              quote_ = other.quote_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuoteIsMutable();
              quote_.addAll(other.quote_);
            }
            onChanged();
          }
        } else {
          if (!other.quote_.isEmpty()) {
            if (quoteBuilder_.isEmpty()) {
              quoteBuilder_.dispose();
              quoteBuilder_ = null;
              quote_ = other.quote_;
              bitField0_ = (bitField0_ & ~0x00000001);
              quoteBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getQuoteFieldBuilder() : null;
            } else {
              quoteBuilder_.addAllMessages(other.quote_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getQuoteCount(); i++) {
          if (!getQuote(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              stockwatch.messages.QuoteMessages.Quote.Builder subBuilder = stockwatch.messages.QuoteMessages.Quote.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addQuote(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .serialized.Quote quote = 1;
      private java.util.List<stockwatch.messages.QuoteMessages.Quote> quote_ =
        java.util.Collections.emptyList();
      private void ensureQuoteIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          quote_ = new java.util.ArrayList<stockwatch.messages.QuoteMessages.Quote>(quote_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          stockwatch.messages.QuoteMessages.Quote, stockwatch.messages.QuoteMessages.Quote.Builder, stockwatch.messages.QuoteMessages.QuoteOrBuilder> quoteBuilder_;
      
      public java.util.List<stockwatch.messages.QuoteMessages.Quote> getQuoteList() {
        if (quoteBuilder_ == null) {
          return java.util.Collections.unmodifiableList(quote_);
        } else {
          return quoteBuilder_.getMessageList();
        }
      }
      public int getQuoteCount() {
        if (quoteBuilder_ == null) {
          return quote_.size();
        } else {
          return quoteBuilder_.getCount();
        }
      }
      public stockwatch.messages.QuoteMessages.Quote getQuote(int index) {
        if (quoteBuilder_ == null) {
          return quote_.get(index);
        } else {
          return quoteBuilder_.getMessage(index);
        }
      }
      public Builder setQuote(
          int index, stockwatch.messages.QuoteMessages.Quote value) {
        if (quoteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuoteIsMutable();
          quote_.set(index, value);
          onChanged();
        } else {
          quoteBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setQuote(
          int index, stockwatch.messages.QuoteMessages.Quote.Builder builderForValue) {
        if (quoteBuilder_ == null) {
          ensureQuoteIsMutable();
          quote_.set(index, builderForValue.build());
          onChanged();
        } else {
          quoteBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addQuote(stockwatch.messages.QuoteMessages.Quote value) {
        if (quoteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuoteIsMutable();
          quote_.add(value);
          onChanged();
        } else {
          quoteBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addQuote(
          int index, stockwatch.messages.QuoteMessages.Quote value) {
        if (quoteBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuoteIsMutable();
          quote_.add(index, value);
          onChanged();
        } else {
          quoteBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addQuote(
          stockwatch.messages.QuoteMessages.Quote.Builder builderForValue) {
        if (quoteBuilder_ == null) {
          ensureQuoteIsMutable();
          quote_.add(builderForValue.build());
          onChanged();
        } else {
          quoteBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addQuote(
          int index, stockwatch.messages.QuoteMessages.Quote.Builder builderForValue) {
        if (quoteBuilder_ == null) {
          ensureQuoteIsMutable();
          quote_.add(index, builderForValue.build());
          onChanged();
        } else {
          quoteBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllQuote(
          java.lang.Iterable<? extends stockwatch.messages.QuoteMessages.Quote> values) {
        if (quoteBuilder_ == null) {
          ensureQuoteIsMutable();
          super.addAll(values, quote_);
          onChanged();
        } else {
          quoteBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearQuote() {
        if (quoteBuilder_ == null) {
          quote_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          quoteBuilder_.clear();
        }
        return this;
      }
      public Builder removeQuote(int index) {
        if (quoteBuilder_ == null) {
          ensureQuoteIsMutable();
          quote_.remove(index);
          onChanged();
        } else {
          quoteBuilder_.remove(index);
        }
        return this;
      }
      public stockwatch.messages.QuoteMessages.Quote.Builder getQuoteBuilder(
          int index) {
        return getQuoteFieldBuilder().getBuilder(index);
      }
      public stockwatch.messages.QuoteMessages.QuoteOrBuilder getQuoteOrBuilder(
          int index) {
        if (quoteBuilder_ == null) {
          return quote_.get(index);  } else {
          return quoteBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends stockwatch.messages.QuoteMessages.QuoteOrBuilder> 
           getQuoteOrBuilderList() {
        if (quoteBuilder_ != null) {
          return quoteBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(quote_);
        }
      }
      public stockwatch.messages.QuoteMessages.Quote.Builder addQuoteBuilder() {
        return getQuoteFieldBuilder().addBuilder(
            stockwatch.messages.QuoteMessages.Quote.getDefaultInstance());
      }
      public stockwatch.messages.QuoteMessages.Quote.Builder addQuoteBuilder(
          int index) {
        return getQuoteFieldBuilder().addBuilder(
            index, stockwatch.messages.QuoteMessages.Quote.getDefaultInstance());
      }
      public java.util.List<stockwatch.messages.QuoteMessages.Quote.Builder> 
           getQuoteBuilderList() {
        return getQuoteFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          stockwatch.messages.QuoteMessages.Quote, stockwatch.messages.QuoteMessages.Quote.Builder, stockwatch.messages.QuoteMessages.QuoteOrBuilder> 
          getQuoteFieldBuilder() {
        if (quoteBuilder_ == null) {
          quoteBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              stockwatch.messages.QuoteMessages.Quote, stockwatch.messages.QuoteMessages.Quote.Builder, stockwatch.messages.QuoteMessages.QuoteOrBuilder>(
                  quote_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          quote_ = null;
        }
        return quoteBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:serialized.QuoteList)
    }
    
    static {
      defaultInstance = new QuoteList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:serialized.QuoteList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serialized_Quote_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialized_Quote_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serialized_QuoteList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serialized_QuoteList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023quoteMessages.proto\022\nserialized\"\326\001\n\005Qu" +
      "ote\022\014\n\004name\030\001 \002(\t\022\n\n\002id\030\002 \002(\t\022\021\n\tlastPri" +
      "ce\030\003 \001(\001\022\030\n\020percentageChange\030\004 \001(\001\022\014\n\004op" +
      "en\030\005 \001(\001\022\013\n\003low\030\006 \001(\001\022\014\n\004high\030\007 \001(\001\022\016\n\006v" +
      "olume\030\010 \001(\005\022\026\n\016lastChangeTime\030\t \001(\t\022\013\n\003l" +
      "op\030\n \001(\005\022\020\n\010lopChane\030\013 \001(\005\022\026\n\016expiration" +
      "Date\030\014 \001(\t\"-\n\tQuoteList\022 \n\005quote\030\001 \003(\0132\021" +
      ".serialized.QuoteB$\n\023stockwatch.messages" +
      "B\rQuoteMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serialized_Quote_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serialized_Quote_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serialized_Quote_descriptor,
              new java.lang.String[] { "Name", "Id", "LastPrice", "PercentageChange", "Open", "Low", "High", "Volume", "LastChangeTime", "Lop", "LopChane", "ExpirationDate", },
              stockwatch.messages.QuoteMessages.Quote.class,
              stockwatch.messages.QuoteMessages.Quote.Builder.class);
          internal_static_serialized_QuoteList_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_serialized_QuoteList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serialized_QuoteList_descriptor,
              new java.lang.String[] { "Quote", },
              stockwatch.messages.QuoteMessages.QuoteList.class,
              stockwatch.messages.QuoteMessages.QuoteList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
